### ISSUE TITLE
docker build fails at pip install -r requirements.txt

### ISSUE THREAD

**Issue by philicibine** [Gentleman1983/ginlong_solis_api_connector#73]
Trying to build this on a second rpi4.  I have it built and running on another one.  But when I do `docker build .` it stops with the following error.
```
#10 [6/7] RUN pip install -r requirements.txt
#10 1.146 Traceback (most recent call last):
#10 1.146   File "/usr/local/bin/pip", line 5, in <module>
#10 1.147     from pip._internal.cli.main import main
#10 1.147   File "/usr/local/lib/python3.12/site-packages/pip/_internal/__init__.py", line 3, in <module>
#10 1.148     from pip._internal.utils import _log
#10 1.148   File "/usr/local/lib/python3.12/site-packages/pip/_internal/utils/_log.py", line 8, in <module>
#10 1.149     import logging
#10 1.149   File "/usr/local/lib/python3.12/logging/__init__.py", line 26, in <module>
#10 1.150     import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
#10 1.150 RuntimeError: invalid GMT offset
#10 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
------
 > [6/7] RUN pip install -r requirements.txt:
1.146 Traceback (most recent call last):
1.146   File "/usr/local/bin/pip", line 5, in <module>
1.147     from pip._internal.cli.main import main
1.147   File "/usr/local/lib/python3.12/site-packages/pip/_internal/__init__.py", line 3, in <module>
1.148     from pip._internal.utils import _log
1.148   File "/usr/local/lib/python3.12/site-packages/pip/_internal/utils/_log.py", line 8, in <module>
1.149     import logging
1.149   File "/usr/local/lib/python3.12/logging/__init__.py", line 26, in <module>
1.150     import sys, os, time, io, re, traceback, warnings, weakref, collections.abc
1.150 RuntimeError: invalid GMT offset
------
WARNING: current commit information was not captured by the build: failed to read current commit information with git rev-parse --is-inside-work-tree
Dockerfile:64
--------------------
  62 |
  63 |     COPY requirements.txt ./
  64 | >>> RUN pip install -r requirements.txt
  65 |
  66 |     COPY ginlong_solis_api_connector.py ./
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by philicibine** [comment]
Fixed it with ```python:2-alpine``` at the start of the Dockerfile
